Using TensorFlow backend.
2019-06-18 13:54:26.862156: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-18 13:54:26.887529: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691555000 Hz
2019-06-18 13:54:26.888223: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55897b4a9790 executing computations on platform Host. Devices:
2019-06-18 13:54:26.888269: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-18 13:54:26.980691: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55897b3a4df0 executing computations on platform CUDA. Devices:
2019-06-18 13:54:26.980739: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-18 13:54:26.981124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 6.94GiB
2019-06-18 13:54:26.981155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-18 13:54:26.982014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-18 13:54:26.982037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-18 13:54:26.982048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-18 13:54:26.982273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6747 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-18 13:54:29.935407: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py:49: UserWarning: Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
  warnings.warn('Not running the attack because the original input'
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "foolbox_exp/cifar_pooling_vs_fc.py", line 215, in <module>
    print([np.math.log(x) for x in linear_mmd])
  File "foolbox_exp/cifar_pooling_vs_fc.py", line 215, in <listcomp>
    print([np.math.log(x) for x in linear_mmd])
ValueError: math domain error
Using TensorFlow backend.
2019-06-18 21:54:24.940003: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-18 21:54:24.963468: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691555000 Hz
2019-06-18 21:54:24.964267: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5628824da980 executing computations on platform Host. Devices:
2019-06-18 21:54:24.964311: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-18 21:54:25.058188: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x562881ee9440 executing computations on platform CUDA. Devices:
2019-06-18 21:54:25.058230: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-18 21:54:25.058605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 5.49GiB
2019-06-18 21:54:25.058630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-18 21:54:25.059482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-18 21:54:25.059503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-18 21:54:25.059511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-18 21:54:25.059727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5323 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-18 21:54:27.943894: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py:49: UserWarning: Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
  warnings.warn('Not running the attack because the original input'
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py:68: UserWarning: CarliniWagnerL2Attack did not find an adversarial, maybe the model or the criterion is not supported by this attack.
  ' attack.'.format(self.name()))
Traceback (most recent call last):
  File "foolbox_exp/cifar_pooling_vs_fc.py", line 164, in <module>
    adv_examples_no_misclassification)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/experiment_models/utils.py", line 72, in mmd_evaluation
    return maximum_mean_discrepancy(x, y, linear_kernel)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/experiment_models/utils.py", line 26, in maximum_mean_discrepancy
    mmd /= (m * (m-1))
ZeroDivisionError: float division by zero
